### ISSUE TITLE
Broken link in Code of Conduct section in README

### ISSUE THREAD

**Issue by udines** [qontak-dev/rahasia#3]
When I click code of conduct hyperlink in README, it redirects to `https://github.com/%5BUSERNAME%5D/rahasia/blob/master/CODE_OF_CONDUCT.md` which returns `Not Found`

![Screenshot from 2020-02-11 16-38-55](https://user-images.githubusercontent.com/15243021/74225317-0f8bc600-4ced-11ea-9d3e-95919d042dd0.png)

*Nyoba submit issue mas.

**Comment by udn** [comment]
Thanks @udines we will update the `CODE_OF_CONDUCT.md` file
